version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: erpgolang-app
    container_name: anierp-app
    restart: unless-stopped
    ports:
      - "8009:8009"
    depends_on:
      - db
    networks:
      - anierp_general

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: anierp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: anierp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - anierp_general

networks:
  anierp_general:
    driver: bridge

volumes:
  db_data:
    driver: local
