version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-app
    container_name: gogeneral-app
    restart: unless-stopped
    ports:
      - "8009:8009"
    depends_on:
      - db
    networks:
      - anierp_general

networks:
  anierp_general:
    driver: bridge

volumes:
  db_data:
    driver: local
