version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: erpgolang-app
    container_name: anierp-app
    restart: unless-stopped
    ports:
      - "8009:8009"
    depends_on:
      - db
    networks:
      - anierp

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: anierp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: anierp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - anierp

  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/amd64
    container_name: anierp-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8010:80"
    networks:
      - anierp

networks:
  anierp:
    driver: bridge

volumes:
  db_data:
    driver: local
